### ISSUE TITLE
unconditional console.log statements

### ISSUE THREAD

**Issue by debugme** [pensierinmusica/csvdata#1]
The code contains console.log statements which execute unconditionally.
Ideally they would be controlled by options passed in by the user.

For example, when I run `csvdata.load('input.csv')` I get the following appearing on the console:

Reading data from input.csv
Parsing data...
Data parsed

**Comment by pensierinmusica** [comment]
Hi, sure that could be changed. We could leave them as default but offer an option to bypass them.

Something like:

``` js
{logging: false}
```

Do you have a specific case where the current logging is a problem / bothering you? Just interested to figure out.

Thanks!

**Comment by debugme** [comment]
I like your idea. 

Keeping the existing behaviour as a default, but being able to override it via options.

Thanks for the awesome work by the way ;)
