### ISSUE TITLE
csvdata with vue webpack not working 

### ISSUE THREAD

**Issue by ghost** [pensierinmusica/csvdata#13]
Hello,
I'm pretty new at developing so might be I'm doing a very silly mistake.
Basically, when I try to do npm run dev it gives me this error: 
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
|
| 'use strict';

 @ ./src/main.js 6:14-32
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

Looks like webpack doesn't like the shebang as when I remove it is working fine. 

Here the step I took that gives me this error:
- vue init webpack my-project
- cd my-project
- npm i --save csvdata
- npm run dev

Any help is appreciated. thank you!

**Comment by pensierinmusica** [comment]
Hi @danielcaseri, csvdata is made to run in Node on the back end, not in the browser.

Cheers!
